Tax tobin asp
bjornnorgaard/ITONK pull request #11
Opened 2017-05-02 18:32 UTC by MartinCarpentier

Jeg har implementeret servicen i .net core i stedet for for fuld .net og nancyfx

2017-05-03 20:12 UTC, bjornnorgaard requested changes
Lige nu kan det ikke bygge, da du har commitet en mergeconflict.

Har lavet en række kommentarer til ændringer der lige skal fixes. Generelt ser det dog meget godt ud. Bare husk at rydde op i dine 'using namespace'. Der er mange som ikke bliver brugt.

Det ser også ud til at der mangler en .gitignore

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/DefaultController.cs
> +}
Tilføj newline til sidst i filen, så bliver git glad.

![image](https://cloud.githubusercontent.com/assets/9103554/25678801/50354abc-304b-11e7-8670-6f95745ec39f.png)

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/TaxController.cs
> +    public class taxController : Controller
C# er PascalCase.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/DefaultController.cs
> +using System;
Ryd op i dine ubrugte namespaces.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/TaxController.cs
> +﻿using System;
Samme igen, ryd op i namespaces

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/TaxController.cs
> +        public taxController(ILogger<taxController> logger, ITaxCalculator taxCalculator, IExternalTaxComms externalTaxComms)
C# er pascalcase

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Controllers/TaxController.cs
> +
fjern redundant newline

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/ExternalTaxComms/ExternalTaxComms.cs
> +﻿using System;
ryd op i namespaces

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/ExternalTaxComms/IExternalTaxComms.cs
> +using TaxTobin.Models;
Kun `using TaxTobin.Models` bliver brugt.

Ryd op i namespaces.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Logs/TaxTobin-20170501.txt
> +2017-05-01T19:46:52.0919572+02:00 0HL4GN86EIAFT [INF] Request starting HTTP/1.1 GET http://localhost:59552/api/values   (e5be5b71)
Log filer skal ikke under versionstyring. Føj til gitignore og fjern fra remote.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Program.cs
> +﻿using System;
Der bliver kun brugt to af alle disse namespaces. Fjern de overskydende.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/ScaffoldingReadMe.txt
> +﻿
Ikke sikker på om denne fil hører til i git. Overvej om den skal blive.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Startup.cs
> +﻿using System;
Ryd op i namespaces

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/TaxCalculations/ITaxCalculator.cs
>  ﻿using System;
Du har commit en mergeconflict. Fix det, tak.

Husk at bygge før du pusher ;)

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/TaxCalculations/ITaxCalculator.cs
>  using System.Collections.Generic;
Overflødige namespaces igen.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/TaxCalculations/ITaxCalculator.cs
> +    public interface ITaxCalculator
Det ligner at der har været et interface og en implementering i denne fil.
De skal være i hver deres fil.

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/TaxCalculations/TaxCalculator.cs
> +﻿using System;
Namespaces igen

2017-05-03 20:12 UTC, bjornnorgaard commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Views/_ViewImports.cshtml
> +@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
Ikke sikker på om filen er autogen eller ej. Hvis du har lavet den så tilføj manglende newline to sidst i filen. Så bliver git glad igen :)

2017-05-04 07:39 UTC, MartinCarpentier commented on services/taxtobin/TaxTobinAspCore/TaxTobin/TaxTobin/Views/_ViewImports.cshtml
> +@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
Det er en autogenereret fil.

2017-05-04 09:14 UTC, closed without merging