Provider/services
bjornnorgaard/ITONK pull request #5
Opened 2017-04-24 13:13 UTC by bjornnorgaard

2017-04-24 13:18 UTC, dentych requested changes
denied

2017-04-24 13:23 UTC, dentych requested changes
pls fix

2017-04-24 13:23 UTC, dentych commented on services/provider/Provider/Services/BrokerService.cs
> +            request.Wait();
await pls

2017-04-24 13:23 UTC, dentych commented on services/provider/Provider/Services/RegistryService.cs
> +            request.Wait();
puha bjørn. async pls

2017-04-24 13:23 UTC, dentych commented on services/provider/Provider/Services/Services.csproj
>  </Project>
buuuuh. mangler newline

2017-04-24 13:32 UTC, bjornnorgaard commented on services/provider/Provider/Services/Services.csproj
>  </Project>
wont fix. fu.

2017-04-24 13:32 UTC, bjornnorgaard commented
stuff has been fixed.

2017-04-27 07:28 UTC, dentych requested changes

2017-04-27 07:28 UTC, dentych commented on services/provider/Provider/Interfaces/IRegistryAddressService.cs
> +    public interface IRegistryAddressService
SO MANY INTERFACES. Such no need til sådan en miniature microservice

2017-04-27 07:28 UTC, dentych commented on services/provider/Provider/Interfaces/IBrokerService.cs
>      public interface IBrokerService
eeeej bjørn. puuuuha

2017-04-27 07:28 UTC, dentych commented on services/provider/Provider/Interfaces/IRegistryService.cs
>      public interface IRegistryService
Arrrrrrrhhhhhh... Skal der nu også være et HELT interface kun til denne? Det tror jeg ikke

2017-04-27 08:19 UTC, bjornnorgaard commented
Hvis du kan sige mig hvordan man injecter et ctor argument på baggrund af navn i dotnet core. Så laver jeg det glædeligt om. 

Till then, no dice.

2017-04-27 08:30 UTC, bjornnorgaard commented on services/provider/Provider/Interfaces/IRegistryAddressService.cs
> +    public interface IRegistryAddressService
It's fiiine!

2017-04-27 08:30 UTC, bjornnorgaard commented on services/provider/Provider/Interfaces/IBrokerService.cs
>      public interface IBrokerService
Piv piv, only minor overkill.

2017-04-27 08:30 UTC, bjornnorgaard commented on services/provider/Provider/Interfaces/IRegistryService.cs
>      public interface IRegistryService
Overkill is underrated.

2017-04-27 09:18 UTC, dentych approved these changes
fint

2017-04-27 09:18 UTC, merged